=== LehaSex/rust-game-icons/.pipeline/schemas/items.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "rust-game-icons items.json",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["category", "id", "image_name", "name"],
    "additionalProperties": false,
    "properties": {
      "category": {
        "type": "string",
        "enum": ["ammo", "attire", "components", "construction", "electrical",
                 "food", "fun", "items", "medical", "misc", "resources",
                 "tools", "traps", "weapons"]
      },
      "id": {"type": "integer"},
      "image_name": {"type": "string", "minLength": 1},
      "name": {
        "type": "object",
        "required": ["en"],
        "additionalProperties": {"type": "string"}
      }
    }
  }
}

=== LehaSex/rust-game-icons/all_items.json
[
  {
    "id": -1685290200,
    "image_name": "ammo.shotgun",
    "name": {
      "en": "12 Gauge Buckshot",
      "ru": "Дробь 12-го калибра"
    },
    "category": "ammo"
  },
  {
    "id": -1036635990,
    "image_name": "ammo.shotgun.fire",
    "name": {
      "en": "12 Gauge Incendiary Shell",
      "ru": "Зажигательный Снаряд 12-го калибра"
    },
    "category": "ammo"
  },
  {
    "id": -727717969,
    "image_name": "ammo.shotgun.slug",
    "name": {
      "en": "12 Gauge Slug",
      "ru": "Пуля 12-го калибра"
    },
    "category": "ammo"
  },
  {
    "id": 349762871,
    "image_name": "ammo.grenadelauncher.he",
    "name": {
      "en": "40mm HE Grenade",
      "ru": "40-мм фугасная граната"
    },
    "category": "ammo"
  },
  {
    "id": 1055319033,
    "image_name": "ammo.grenadelauncher.buckshot",
    "name": {
      "en": "40mm Shotgun Round",
      "ru": "40-мм картечь"
    },
    "category": "ammo"
  },
  {
    "id": 915408809,
    "image_name": "ammo.grenadelauncher.smoke",
    "name": {
      "en": "40mm Smoke Grenade",
      "ru": "40-мм дымовая граната"
    },
    "category": "ammo"
  },
  {
    "id": -1211166256,
    "image_name": "ammo.rifle",
    "name": {
      "en": "5.56 Rifle Ammo",
      "ru": "Патроны 5.56-мм"
    },
    "category": "ammo"
  },
  {
    "id": 1954597876,
    "image_name": "catapult.ammo.bee",
    "name": {
      "en": "Bee Catapult Bomb",
      "ru": "Пчелиная бомба для катапульты"
    },
    "category": "ammo"
  },
  {
    "id": 215754713,
    "image_name": "arrow.bone",
    "name": {
      "en": "Bone Arrow",
      "ru": "Костяная стрела"
    },
    "category": "ammo"
  },
  {
    "id": -411735114,
    "image_name": "cannonball",
    "name": {
      "en": "Cannonball",
      "ru": "Пушечное ядро"
    },
    "category": "ammo"
  },
  {
    "id": -1321651331,
    "image_name": "ammo.rifle.explosive",
    "name": {
      "en": "Explosive 5.56 Rifle Ammo",
      "ru": "Патрон 5.56 мм (Разрывной)"
    },
    "category": "ammo"
  },
  {
    "id": 14241751,
    "image_name": "arrow.fire",
    "name": {
      "en": "Fire Arrow",
      "ru": "Огненная стрела"
    },
    "category": "ammo"
  },
  {
    "id": -484006286,
    "image_name": "catapult.ammo.incendiary",
    "name": {
      "en": "Firebomb",
      "ru": "Зажигательная бомба"
    },
    "category": "ammo"
  },
  {
    "id": -486432631,
    "image_name": "ammo.mortar.fragment",
    "name": {
      "en": "Fragmentation Mortar Shell",
      "ru": "Осколочный минометный снаряд"
    },
    "category": "ammo"
  },
  {
    "id": 1712070256,
    "image_name": "ammo.rifle.hv",
    "name": {
      "en": "HV 5.56 Rifle Ammo",
      "ru": "Патрон 5.56-мм (скоростной)"
    },
    "category": "ammo"
  },
  {
    "id": -1691396643,
    "image_name": "ammo.pistol.hv",
    "name": {
      "en": "HV Pistol Ammo",
      "ru": "Скоростной пистолетный патрон"
    },
    "category": "ammo"
  },
  {
    "id": -19318653,
    "image_name": "ballista.bolt.hammerhead",
    "name": {
      "en": "Hammerhead Bolt",
      "ru": "Болт-молот"
    },
    "category": "ammo"
  },
  {
    "id": 588596902,
    "image_name": "ammo.handmade.shell",
    "name": {
      "en": "Handmade Shell",
      "ru": "Самодельный патрон"
    },
    "category": "ammo"
  },
  {
    "id": -1023065463,
    "image_name": "arrow.hv",
    "name": {
      "en": "High Velocity Arrow",
      "ru": "Скоростная стрела"
    },
    "category": "ammo"
  },
  {
    "id": -1841918730,
    "image_name": "ammo.rocket.hv",
    "name": {
      "en": "High Velocity Rocket",
      "ru": "Скоростная ракета"
    },
    "category": "ammo"
  },
  {
    "id": 1296788329,
    "image_name": "ammo.rocket.seeker",
    "name": {
      "en": "Homing Missile",
      "ru": "Ракета ПЗРК"
    },
    "category": "ammo"
  },
  {
    "id": -963819285,
    "image_name": "dart.incapacitate",
    "name": {
      "en": "Incapacitate Dart",
      "ru": "Оглушающий дротик"
    },
    "category": "ammo"
  },
  {
    "id": 605467368,
    "image_name": "ammo.rifle.incendiary",
    "name": {
      "en": "Incendiary 5.56 Rifle Ammo",
      "ru": "Патрон 5.56 мм (зажигательный)"
    },
    "category": "ammo"
  },
  {
    "id": -1987565603,
    "image_name": "ballista.bolt.incendiary",
    "name": {
      "en": "Incendiary Bolt",
      "ru": "Зажигательный болт"
    },
    "category": "ammo"
  },
  {
    "id": 51984655,
    "image_name": "ammo.pistol.fire",
    "name": {
      "en": "Incendiary Pistol Bullet",
      "ru": "Зажигательный пистолетный патрон"
    },
    "category": "ammo"
  },
  {
    "id": 1638322904,
    "image_name": "ammo.rocket.fire",
    "name": {
      "en": "Incendiary Rocket",
      "ru": "Зажигательная ракета"
    },
    "category": "ammo"
  },
  {
    "id": -1843426638,
    "image_name": "ammo.rocket.mlrs",
    "name": {
      "en": "MLRS Rocket",
      "ru": "Ракета РСЗО"
    },
    "category": "ammo"
  },
  {
    "id": 963150711,
    "image_name": "ammo.mortar.basic",
    "name": {
      "en": "Mortar Shell",
      "ru": "Миномётный снаряд"
    },
    "category": "ammo"
  },
  {
    "id": -2097376851,
    "image_name": "ammo.nailgun.nails",
    "name": {
      "en": "Nailgun Nails",
      "ru": "Гвозди"
    },
    "category": "ammo"
  },
  {
    "id": 385645417,
    "image_name": "ammo.paintball",
    "name": {
      "en": "Paintball",
      "ru": "Пейнтбольный шарик"
    },
    "category": "ammo"
  },
  {
    "id": -1127003365,
    "image_name": "ballista.bolt.piercer",
    "name": {
      "en": "Piercer Bolt",
      "ru": "Бронебойный болт"
    },
    "category": "ammo"
  },
  {
    "id": 785728077,
    "image_name": "ammo.pistol",
    "name": {
      "en": "Pistol Bullet",
      "ru": "Пистолетный патрон"
    },
    "category": "ammo"
  },
  {
    "id": -357442017,
    "image_name": "ballista.bolt.pitchfork",
    "name": {
      "en": "Pitchfork Bolt",
      "ru": "Болт вилы"
    },
    "category": "ammo"
  },
  {
    "id": -1827561369,
    "image_name": "catapult.ammo.explosive",
    "name": {
      "en": "Propane Explosive Bomb",
      "ru": "Пропановая Бомба"
    },
    "category": "ammo"
  },
  {
    "id": -594596146,
    "image_name": "dart.radiation",
    "name": {
      "en": "Radiation Dart",
      "ru": "Радиационный дротик"
    },
    "category": "ammo"
  },
  {
    "id": -742865266,
    "image_name": "ammo.rocket.basic",
    "name": {
      "en": "Rocket",
      "ru": "Ракета"
    },
    "category": "ammo"
  },
  {
    "id": -384243979,
    "image_name": "ammo.rocket.sam",
    "name": {
      "en": "SAM Ammo",
      "ru": "Зенитная управляемая ракета"
    },
    "category": "ammo"
  },
  {
    "id": 2036395619,
    "image_name": "dart.scatter",
    "name": {
      "en": "Scatter Dart",
      "ru": "Дротик с дробью"
    },
    "category": "ammo"
  },
  {
    "id": 1831249347,
    "image_name": "catapult.ammo.boulder",
    "name": {
      "en": "Scattershot",
      "ru": "Каменная дробь"
    },
    "category": "ammo"
  },
  {
    "id": -17123659,
    "image_name": "ammo.rocket.smoke",
    "name": {
      "en": "Smoke Rocket WIP!!!!",
      "ru": "Ракета (Дымовая) В РАЗРАБОТКЕ!"
    },
    "category": "ammo"
  },
  {
    "id": -1800345240,
    "image_name": "speargun.spear",
    "name": {
      "en": "Speargun Spear",
      "ru": "Гарпун"
    },
    "category": "ammo"
  },
  {
    "id": -1671551935,
    "image_name": "submarine.torpedo.straight",
    "name": {
      "en": "Torpedo",
      "ru": "Торпеда"
    },
    "category": "ammo"
  },
  {
    "id": -274709858,
    "image_name": "dart.wood",
    "name": {
      "en": "Wood Dart",
      "ru": "Деревянный дротик"
    },
    "category": "ammo"
  },
  {
    "id": -1234735557,
    "image_name": "arrow.wooden",
    "name": {
      "en": "Wooden Arrow",
      "ru": "Деревянная стрела"
    },
    "category": "ammo"
  },
  {
    "id": -1215166612,
    "image_name": "barrelcostume",
    "name": {
      "en": "A Barrel Costume",
      "ru": "Костюм бочки"
    },
    "category": "attire"
  },
  {
    "id": 1107575710,
    "image_name": "hazmatsuit_scientist_arctic",
    "name": {
      "en": "Arctic Scientist Suit",
      "ru": "Костюм арктического ученого"
    },
    "category": "attire"
  },
  {
    "id": -470439097,
    "image_name": "hazmatsuit.arcticsuit",
    "name": {
      "en": "Arctic Suit",
      "ru": "Арктический Костюм"
    },
    "category": "attire"
  },
  {
    "id": 1468749025,
    "image_name": "bdu.pants",
    "name": {
      "en": "BDU Pants",
      "ru": "Армейские штаны"
    },
    "category": "attire"
  },
  {
    "id": -2127311451,
    "image_name": "bdu.shirt",
    "name": {
      "en": "BDU Shirt",
      "ru": "Армейская рубашка"
    },
    "category": "attire"
  },
  {
    "id": 1983541158,
    "image_name": "ballistic.legarmor",
    "name": {
      "en": "Ballistic Leg Armour",
      "ru": "Баллистическая броня для ног"
    },
    "category": "attire"
  },
  {
    "id": -1780402255,
    "image_name": "ballistic.vest",
    "name": {
      "en": "Ballistic Vest",
      "ru": "Баллистический жилет"
    },
    "category": "attire"
  },
  {
    "id": 1127732084,
    "image_name": "ballistic.helmet",
    "name": {
      "en": "Ballistic helmet",
      "ru": "Баллистический шлем"
    },
    "category": "attire"
  },
  {
    "id": -702051347,
    "image_name": "mask.bandana",
    "name": {
      "en": "Bandana Mask",
      "ru": "Бандана"
    },
    "category": "attire"
  },
  {
    "id": -1622110948,
    "image_name": "attire.banditguard",
    "name": {
      "en": "Bandit Guard Gear",
      "ru": "Одежда бандита-охранника"
    },
    "category": "attire"
  },
  {
    "id": -1022661119,
    "image_name": "hat.cap",
    "name": {
      "en": "Baseball Cap",
      "ru": "Кепка"
    },
    "category": "attire"
  },
  {
    "id": -1211268013,
    "image_name": "horse.shoes.basic",
    "name": {
      "en": "Basic Horse Shoes",
      "ru": "Обычные подковы"
    },
    "category": "attire"
  },
  {
    "id": 1675639563,
